name: UltraRedFreedomMod Remastered
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
<<<<<<< Updated upstream
version: 2.1
=======
version: 3.6
>>>>>>> Stashed changes
description: Plugin for the Total Freedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, Prozza, PacksGamingHD]

# plugin.yml is no longer used to define commands.
